"""Alinear esquema con modelos

Revision ID: 9c5417157517
Revises: 
Create Date: 2026-09-25 22:40:32.505911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5417157517'
down_revision = None
branch_labels = None
depends_on = None

ID_TABLES = (
    'administradores',
    'categorias',
    'colecciones',
    'colores_producto',
    'etiquetas',
    'imagenes_producto',
    'movimientos_stock',
    'pedido_items',
    'pedidos',
    'productos',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))

    op.execute(sa.text(
        "UPDATE public.administradores "
        "SET creado_en = CURRENT_TIMESTAMP AT TIME ZONE 'UTC' "
        "WHERE creado_en IS NULL"
    ))

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.alter_column(
            'creado_en',
            existing_type=sa.DateTime(),
            nullable=False,
            existing_nullable=True,
        )

    with op.batch_alter_table('movimientos_stock', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    for table_name in ID_TABLES:
        op.execute(sa.text(
            f'ALTER TABLE public."{table_name}" '
            'ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY'
        ))
        op.execute(sa.text(
            f"SELECT setval(pg_get_serial_sequence('public.{table_name}', 'id'), "
            f'COALESCE((SELECT MAX(id) + 1 FROM public."{table_name}"), 1), false)'
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in reversed(ID_TABLES):
        op.execute(sa.text(
            f'ALTER TABLE public."{table_name}" '
            'ALTER COLUMN id DROP IDENTITY IF EXISTS'
        ))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('movimientos_stock', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_column('creado_en')

    # ### end Alembic commands ###
